# Assemblage Makefile

# Configuration

PYTHON="/path/to/python"
PYDOC="/path/to/pydoc"
EASYINSTALL="/path/to/easy_install"
NOSETESTS="/path/to/nosetests"

# Targets

console:
	export PYTHONPATH=${PYTHONPATH}:src/ && ${PYTHON}

docs:
	mkdir -p docs
	${PYDOC} -w src/assemblage.py
	mv assemblage.html docs

deps:
	${EASYINSTALL} nose
	${EASYINSTALL} mocker

test:
	${NOSETESTS} -i should -i spec --verbose --nocapture

clean:
	find . -name *.pyc -exec rm {} \;
	rm -rf docs

.PHONY: console test clean
