# Assemblage Makefile

# Configuration

PYTHON="/path/to/python"
PYDOC="/path/to/pydoc"
EASYINSTALL="/path/to/easy_install"
NOSETESTS="/path/to/nosetests"

# Targets

console:
	export PYTHONPATH=${PYTHONPATH}:src/ && ${PYTHON}

docs:
	mkdir -p docs
	${PYDOC} -w src/assemblage.py
	mv assemblage.html docs

deps:
	${EASYINSTALL} nose
	${EASYINSTALL} mocker

test:
	${NOSETESTS} -i should -i spec --verbose --nocapture

dist: clean
	cd src && ./setup.py sdist
	cp src/dist/* .
	rm -rf src/dist
	rm -rf src/*.egg-info

clean:
	find . -name *.pyc -exec rm {} \;
	rm -rf docs
	rm -rf *.tar.gz

.PHONY: console test clean